package lnyswz.doc.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TButton generated by hbm2java
 */
@Entity
@Table(name = "t_button")
public class TButton implements java.io.Serializable {

	private String id;
	private TMenu TMenu;
	private String text;
	private String handler;
	private int orderNum;
	private int tabId;
	private String iconCls;// 前面的小图标样式
	
	public TButton() {
	}

	public TButton(String id, TMenu TMenu, String text, String handler,
			int orderNum, int tabId, String iconCls) {
		this.id = id;
		this.TMenu = TMenu;
		this.text = text;
		this.handler = handler;
		this.orderNum = orderNum;
		this.tabId = tabId;
		this.iconCls = iconCls;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menuId", nullable = false)
	public TMenu getTMenu() {
		return this.TMenu;
	}

	public void setTMenu(TMenu TMenu) {
		this.TMenu = TMenu;
	}

	@Column(name = "text", unique = true, nullable = false, length = 100)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "handler")
	public String getHandler() {
		return this.handler;
	}

	public void setHandler(String handler) {
		this.handler = handler;
	}

	@Column(name = "orderNum", nullable = false)
	public int getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(int orderNum) {
		this.orderNum = orderNum;
	}
	
	@Column(name = "tabId", nullable = false)
	public int getTabId() {
		return tabId;
	}

	public void setTabId(int tabId) {
		this.tabId = tabId;
	}

	@Column(name = "iconCls", length = 50)
	public String getIconCls() {
		return iconCls;
	}

	public void setIconCls(String iconCls) {
		this.iconCls = iconCls;
	}
	
}
