package lnyswz.doc.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TMenu generated by hbm2java
 */
@Entity
@Table(name = "t_menu")
public class TMenu implements java.io.Serializable {

	private String id;
	private TCatalog TCatalog;
	private TMenu TMenu;
	private String text;
	private String url;
	private int orderNum;
	private String iconCls;// 前面的小图标样式
	private String lx;
	private String query;
	private Set<TButton> TButtons = new HashSet<TButton>(0);
	private Set<TMenu> TMenus = new HashSet<TMenu>(0);

	public TMenu() {
	}

	public TMenu(String id, TCatalog TCatalog, TMenu TMenu, String text,
			String url, int orderNum, String iconCls, Set<TButton> TButtons, Set<TMenu> TMenus) {
		this.id = id;
		this.TCatalog = TCatalog;
		this.TMenu = TMenu;
		this.text = text;
		this.url = url;
		this.orderNum = orderNum;
		this.iconCls = iconCls;
		this.TButtons = TButtons;
		this.TMenus = TMenus;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cid")
	public TCatalog getTCatalog() {
		return this.TCatalog;
	}

	public void setTCatalog(TCatalog TCatalog) {
		this.TCatalog = TCatalog;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pid")
	public TMenu getTMenu() {
		return this.TMenu;
	}

	public void setTMenu(TMenu TMenu) {
		this.TMenu = TMenu;
	}

	@Column(name = "text", nullable = false, length = 100)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	@Column(name = "url")
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Column(name = "orderNum", nullable = false)
	public int getOrderNum() {
		return this.orderNum;
	}

	public void setOrderNum(int orderNum) {
		this.orderNum = orderNum;
	}
	
	@Column(name = "iconCls", length = 50)
	public String getIconCls() {
		return iconCls;
	}

	public void setIconCls(String iconCls) {
		this.iconCls = iconCls;
	}

	@Column(name = "lx", length = 2)
	public String getLx() {
		return lx;
	}

	public void setLx(String lx) {
		this.lx = lx;
	}

	@Column(name = "query", length = 50)
	public String getQuery() {
		return query;
	}

	public void setQuery(String query) {
		this.query = query;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TMenu", cascade=CascadeType.REMOVE)
	public Set<TButton> getTButtons() {
		return this.TButtons;
	}

	public void setTButtons(Set<TButton> TButtons) {
		this.TButtons = TButtons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TMenu")
	public Set<TMenu> getTMenus() {
		return this.TMenus;
	}

	public void setTMenus(Set<TMenu> TMenus) {
		this.TMenus = TMenus;
	}

}
