package lnyswz.doc.model;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

	/**
	 * TOperalog generated by hbm2java
	 */
	@Entity
	@Table(name = "t_operalog")
	public class TOperalog implements java.io.Serializable {

		private String id;
		private Date logTime;
		private int userId;
		private String bmbh;
		private String menuId;
		private String operation; 
		private String keyId;
		public TOperalog() {
		}

		public TOperalog(String id,Date logTime, int userId,String bmbh,String menuId,String operation,String keyId){
			this.id = id;
			this.logTime = logTime;
			this.userId = userId;
			this.bmbh=bmbh;
			this.menuId=menuId;
			this.operation=operation;
			this.keyId=keyId;
		}
		@Id
		@GeneratedValue(strategy=GenerationType.IDENTITY)
		@Column(name = "id", unique = true, nullable = false, length = 36) 
		public String getId() {
			return this.id;
		}

		public void setId(String id) {
			this.id = id;
		}
		@Temporal(TemporalType.TIMESTAMP)
		@Column(name = "logTime", nullable = false, length = 23)
		public Date getLogTime() {
			return this.logTime;
		}

		public void setLogTime(Date logTime) {
			this.logTime = logTime;
		}

		@Column(name = "userId", nullable = false)
		public int getUserId() {
			return this.userId;
		}

		public void setUserId(int userId) {
			this.userId = userId;
		}
		
		@Column(name = "bmbh", nullable = false, length = 36)
		public String getBmbh() {
			return this.bmbh;
		}

		public void setBmbh(String bmbh) {
			this.bmbh = bmbh;
		}

		
		@Column(name = "menuId", nullable = true, length = 50)
		public String getMenuId() {
			return this.menuId;
		}

		public void setMenuId(String menuId) {
			this.menuId = menuId;
		}
		
		@Column(name = "operation", nullable = false, length = 100)
		public String getOperation() {
			return this.operation;
		}

		public void setOperation(String operation) {
			this.operation = operation;
		}
		@Column(name = "keyId", nullable = false, length = 50)
		public String getKeyId() {
			return this.keyId;
		}

		public void setKeyId(String keyId) {
			this.keyId = keyId;
		}
	}


