package lnyswz.doc.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TPost generated by hbm2java
 */
@Entity
@Table(name = "t_post")
public class TPost implements java.io.Serializable {

	private String id;
	private String postName;
	//王文阳 2013.10.12
	private int orderNum;
	

	public TPost() {
	}

	public TPost(String id) {
		this.id = id;
	}

	public TPost(String id, String postName, int orderNum) {
		this.id = id;
		this.postName = postName;
		this.orderNum = orderNum;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 2)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "postName", unique = true, length = 50)
	public String getPostName() {
		return this.postName;
	}

	public void setPostName(String postName) {
		this.postName = postName;
	}

	public int getOrderNum() {
		return orderNum;
	}

	public void setOrderNum(int orderNum) {
		this.orderNum = orderNum;
	}
}
