package lnyswz.doc.model;
// Generated 2013-8-14 10:42:53 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TRole generated by hbm2java
 */
@Entity
@Table(name = "t_role")
public class TRole implements java.io.Serializable {

	private String id;
	private String roleName;
	private String description;
	private TDepartment TDepartment;
	private Set<TUser> TUsers = new HashSet<TUser>(0);
	private Set<TMenu> TMenus = new HashSet<TMenu>(0);
	private Set<TButton> TButtons = new HashSet<TButton>(0);

	public TRole() {
	}

	public TRole(String id, String roleName, String description,
			Set<TUser> TUsers, Set<TMenu> TMenus, Set<TButton> TButtons) {
		this.id = id;
		this.roleName = roleName;
		this.description = description;
		this.TUsers = TUsers;
		this.TMenus = TMenus;
		this.TButtons = TButtons;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "roleName", unique = true, nullable = false, length = 100)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}
	
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "depId", nullable = true)
	public TDepartment getTDepartment() {
		return TDepartment;
	}

	public void setTDepartment(TDepartment tDepartment) {
		TDepartment = tDepartment;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_user_role", joinColumns = { @JoinColumn(name = "roleId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "userId", nullable = false, updatable = false) })
	public Set<TUser> getTUsers() {
		return this.TUsers;
	}

	public void setTUsers(Set<TUser> TUsers) {
		this.TUsers = TUsers;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_role_menu", joinColumns = { @JoinColumn(name = "roleId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "menuId", nullable = false, updatable = false) })
	public Set<TMenu> getTMenus() {
		return this.TMenus;
	}

	public void setTMenus(Set<TMenu> TMenus) {
		this.TMenus = TMenus;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "t_role_button", joinColumns = { @JoinColumn(name = "roleId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "btnId", nullable = false, updatable = false) })
	public Set<TButton> getTButtons() {
		return this.TButtons;
	}

	public void setTButtons(Set<TButton> TButtons) {
		this.TButtons = TButtons;
	}

}
