package lnyswz.doc.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

// Generated 2013-8-14 10:42:53 by Hibernate Tools 4.0.0

/**
 * TUser generated by hbm2java
 */
@Entity
@Table(name = "t_updateLog")
public class TUpdateLog implements java.io.Serializable {

	private String id;
	private String contents;
	private Date updateTime;
	private String updateDate;
	private String updateUser;

	public TUpdateLog() {
	}

	public TUpdateLog(String id, String contents, Date updateTime,
			String updateDate, String updateUser) {
		this.id = id;
		this.contents = contents;
		this.updateTime = updateTime;
		this.updateDate = updateDate;
		this.updateUser = updateUser;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "contents", unique = true, nullable = false)
	public String getContents() {
		return this.contents;
	}

	public void setContents(String contents) {
		this.contents = contents;
	}

	@Column(name = "updateUser", unique = true, nullable = true)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

	@Column(name = "updateDate", unique = true, nullable = false)
	public String getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(String updateDate) {
		this.updateDate = updateDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updateTime", length = 23)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
